spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/askseniordb}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:Diya@2005}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

server.port=${PORT:8081}

app.upload.dir=${UPLOAD_DIR:uploads}
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB

app.admin.key=${ADMIN_KEY:chaipiladoaurburgerkhiladokoi@123}

app.cors.allowed-origins=${CORS_ORIGINS:http://localhost:3000,http://localhost:5173}
server.address=0.0.0.0